services:
#    admin.example:
#        class: MaximPrihodko\Bundle\AdminBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    admin.sonata.company:
        class: MaximPrihodko\Bundle\AdminBundle\Admin\CompanyAdmin
        arguments: [~, MaximPrihodko\Bundle\AppBundle\Entity\Company, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Компания }
        public: true

    admin.sonata.user_data:
        class: MaximPrihodko\Bundle\AdminBundle\Admin\UserDataAdmin
        arguments: [~, MaximPrihodko\Bundle\AppBundle\Entity\user\User, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Пользователь }
        public: true
