<?php

namespace AppBundle\Repository;

/**
 * ProdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProdRepository extends \Doctrine\ORM\EntityRepository
{
}
