app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

frontend_panel:
    resource: "@FrontendPanelBundle/Resources/config/routing.yml"
    prefix:   /panel

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

api:
    #resource: "@ApiBundle/Resources/config/routing.yml"
    resource: '@ApiBundle/Controller/DefaultController.php'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin