user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /user

api:
    resource: "@ApiBundle/Resources/config/routing.yml"
    prefix:   /api

app:
    resource: '@AppBundle/Controller/'
    type: annotation
