app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

frontend_panel:
    resource: "@FrontendPanelBundle/Resources/config/routing.yml"
    prefix:   /panel

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

api:
    resource: "@ApiBundle/Resources/config/routing.yml"
    prefix:   /api

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"