<?php

namespace MaximPrihodko\Bundle\AppBundle\Repository\voter;

/**
 * VoterAccessRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoterAccessRepository extends \Doctrine\ORM\EntityRepository
{
}
