<?php

namespace MaximPrihodko\Bundle\AppBundle\Repository\voter;

/**
 * VoterGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoterGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
