<?php

namespace MaximPrihodko\Bundle\AppBundle\Repository\user;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserDataRepository extends \Doctrine\ORM\EntityRepository
{

}
