user.index:
    path:     /
    defaults: { _controller: UserBundle:Default:index }

#user.login_check:
#    path:     /login-check
#    defaults: { _controller: UserBundle:Security:loginCheck }

user.login:
    path:     /login
    defaults: { _controller: UserBundle:Security:login }