services:
#    user.example:
#        class: MaximPrihodko\Bundle\UserBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    MaximPrihodko\Bundle\UserBundle\Repository\UserRepository:
        factory:    'doctrine.orm.entity_manager:getRepository'
        arguments:  ['MaximPrihodko\Bundle\UserBundle\Entity\User']