services:
#    user.example:
#        class: MaximPrihodko\Bundle\UserBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    #user.after_login:
    #    class: MaximPrihodko\Bundle\UserBundle\EventListner\AfterLoginListener
     #   arguments: ['@router']
     #   tags:
     #       - { name: kernel.event_subscriber }

################ CONTROLLERS
    MaximPrihodko\Bundle\UserBundle\Controller\SecurityController:
        class: MaximPrihodko\Bundle\UserBundle\Controller\SecurityController
        arguments: ['@user.plain_user_object']

###############
    user.authentication_utils.value_resolver:
        class: MaximPrihodko\Bundle\UserBundle\ArgumentResolver\AuthenticationUtilsValueResolver
        arguments: ['@security.token_storage', '@service_container']
        tags:
            - { name: controller.argument_value_resolver, priority: 50 }


    user.plain_user_object:
        class: MaximPrihodko\Bundle\UserBundle\Model\UserModelPlainObject


    user.security.authentification_handler:
        class: MaximPrihodko\Bundle\UserBundle\Security\AuthenticationHandler
        arguments: ['@router', '@session', '@translator.default']



    redirect.after.login:
        class:  MaximPrihodko\Bundle\UserBundle\Redirection\AfterLoginRedirection
        arguments: ['@router']

    redirect.after.logout:
        class: MaximPrihodko\Bundle\UserBundle\Redirection\AfterLogoutRedirection
        arguments: ['@router']

